name: Tauri Android Build

on:
  push:
    branches:
      - main  # Set this to your default branch
  pull_request:
    branches:
      - main  # Set this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set the Node.js version you are using

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: |
          npm install
          # If you're using pnpm instead of npm, uncomment the following line:
          # pnpm install

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk
          # Install Android SDK
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O android-sdk.zip
          unzip android-sdk.zip
          mkdir "$ANDROID_SDK_ROOT"
          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses > /dev/null
          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-31" "build-tools;31.0.0" > /dev/null
          echo "$ANDROID_SDK_ROOT/platform-tools" >>$GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/build-tools/31.0.0" >>$GITHUB_PATH

      - name: Build Android App
        run: |
          npm run tauri:build
          # If you're using pnpm instead of npm, uncomment the following line:
          # pnpm run tauri:build

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: src-tauri/target/release/bundle/android/app/build/outputs/apk/release/*.apk
